### ISSUE TITLE
Add a description explaining how to select your role

### ISSUE THREAD

**Issue by kmcrayton7** [kmcrayton7/jr_dev_mentoring#30]
Add a description to the profiles page that explains that members can select either the role of mentor, mentee or both.

<img width="362" alt="jrdevmentoring" src="https://cloud.githubusercontent.com/assets/9155255/22793411/c12614ce-eebd-11e6-86f7-f6a7939eb980.png">

**Comment by natethinks** [comment]
Work done on branch issue-30 https://github.com/kmcrayton7/jr_dev_mentoring/pull/33

**Comment by SundayAdefila** [comment]
This has been merged in now, and resolved!
