### ISSUE TITLE
Profile creation/updating gives error

### ISSUE THREAD

**Issue by SundayAdefila** [kmcrayton7/jr_dev_mentoring#5]
Trying to save a profile gives error: 
`An error occurred and your profile has not been updated. You must complete all form fields`

**Comment by erinpagemd** [comment]
@kmcrayton7 I can take this one.

**Comment by erinpagemd** [comment]
A fix for this was merged in to dev https://github.com/kmcrayton7/jr_dev_mentoring/pull/16

**Comment by SundayAdefila** [comment]
Deployed and confirmed resolved! Thanks Erin. I think we can close this now.

**Comment by SundayAdefila** [comment]
Resolved, closing...
