### ISSUE TITLE
Extract out the mentor/mentee plan from registration process.

### ISSUE THREAD

**Issue by kmcrayton7** [kmcrayton7/jr_dev_mentoring#7]
Currently, members have to choose to sign up either Mentor or Mentee. This configuration requires a member to have multiple memberships if they also desire to be both a Mentor AND Mentee. I would like one sign up process that allows members to register as a Mentor, Mentee or post an internship opportunity by choosing all of those roles they'd like to have in one place.

**Comment by SundayAdefila** [comment]
There is a PR available for this now at #18
